// Generated by npm run models:catalog. Source: public/demo/meshes.
export const MODEL_FILES = [
  "Acesjustforroomshow.obj",
  "Arrow.obj",
  "Atom.obj",
  "Birdskull.obj",
  "Blackkey.obj",
  "Blob.obj",
  "Cat.obj",
  "Catskull.obj",
  "Chessboard.obj",
  "Coin.obj",
  "Coingrounded.obj",
  "Cow.obj",
  "Cowskull.obj",
  "Crocodileskull.obj",
  "Cube.obj",
  "CubeGrounded.obj",
  "Cuboctahedron.obj",
  "Cymbal.obj",
  "Dag.obj",
  "Dagtav.obj",
  "Dish.obj",
  "Dodecahedron.obj",
  "Dtmo.obj",
  "Elephantskull.obj",
  "Ernie_model.glb",
  "Ernie_model.obj",
  "Europa.obj",
  "Eyeball.obj",
  "Fourdashtwo.obj",
  "Ganesh.obj",
  "Ganesh_gr.obj",
  "Gargoyle.obj",
  "Gear.obj",
  "Goat.obj",
  "Grin.obj",
  "Hideous1.obj",
  "Hideous2.obj",
  "Horn.obj",
  "Horseskull.obj",
  "Humanskull.obj",
  "Icosahedron.obj",
  "Kbdalow.obj",
  "Kbdanat.obj",
  "Kbdasharp.obj",
  "Kbdbnat.obj",
  "Kbdchigh.obj",
  "Kbdcnat.obj",
  "Kbdcsharp.obj",
  "Kbddnat.obj",
  "Kbddsharp.obj",
  "Kbdenat.obj",
  "Kbdfnat.obj",
  "Kbdfsharp.obj",
  "Kbdgnat.obj",
  "Kbdgsharp.obj",
  "Kbdnata.obj",
  "Kbdnatalow.obj",
  "Kbdnatb.obj",
  "Kbdnatc.obj",
  "Kbdnatchigh.obj",
  "Kbdnatd.obj",
  "Kbdnate.obj",
  "Kbdnatf.obj",
  "Kbdnatg.obj",
  "Kbdsharpa.obj",
  "Kbdsharpc.obj",
  "Kbdsharpd.obj",
  "Kbdsharpf.obj",
  "Kbdsharpg.obj",
  "Kira_model.glb",
  "Kira_model.obj",
  "LRO.obj",
  "Laughingmouth.obj",
  "Lildit.obj",
  "Lobster.obj",
  "MRO.obj",
  "Malehead.obj",
  "Musicnote.obj",
  "N00.obj",
  "N01.obj",
  "N02.obj",
  "N03.obj",
  "N04.obj",
  "N05.obj",
  "N06.obj",
  "N07.obj",
  "N08.obj",
  "N09.obj",
  "N10.obj",
  "N11.obj",
  "N12.obj",
  "N13.obj",
  "N14.obj",
  "N15.obj",
  "N16.obj",
  "Octahedron.obj",
  "Pedal.obj",
  "Perseverance.obj",
  "Pixiewarrior.obj",
  "Pluscube.obj",
  "Ratskull.obj",
  "Rooster.obj",
  "Sheep.obj",
  "Stanfordbunny.obj",
  "Star.obj",
  "Stellateddodecahedron.obj",
  "String.obj",
  "Suzanne.obj",
  "Tav.obj",
  "Teapot.obj",
  "Testplus.obj",
  "Testtet.obj",
  "Tet.obj",
  "Tetrahedron.obj",
  "Thaidrop.obj",
  "Tinker.obj",
  "Tinkerbell.obj",
  "Tinkerbell3.obj",
  "Torus.obj",
  "Triangleflat.obj",
  "Troll.obj",
  "Troll2.obj",
  "Truncatedcube.obj",
  "Twistytorus.obj",
  "Voyager.obj",
  "Wheelsmall.obj",
  "Whitekey.obj",
  "Whitekeytaper.obj",
  "Wiredodecahedron.obj",
  "Wirehexahedron.obj",
  "Wireicosahedron.obj",
  "Wireoctahedron.obj",
  "Wiretetrahedron.obj",
  "Wolf.obj"
];
export const MODEL_MOVEMENTS: Record<string, {name:string;clip:string}[]> = {
  "Ernie_movements.json": [
    {
      "name": "Head nod",
      "clip": "01_Head_nod"
    },
    {
      "name": "Look left",
      "clip": "02_Look_left"
    },
    {
      "name": "Look right",
      "clip": "03_Look_right"
    },
    {
      "name": "Head tilt left",
      "clip": "04_Head_tilt_left"
    },
    {
      "name": "Head tilt right",
      "clip": "05_Head_tilt_right"
    },
    {
      "name": "Chin lift",
      "clip": "06_Chin_lift"
    },
    {
      "name": "Sniff",
      "clip": "07_Sniff"
    },
    {
      "name": "Meow",
      "clip": "08_Meow"
    },
    {
      "name": "Left ear flick",
      "clip": "09_Left_ear_flick"
    },
    {
      "name": "Right ear flick",
      "clip": "10_Right_ear_flick"
    },
    {
      "name": "Ears perk",
      "clip": "11_Ears_perk"
    },
    {
      "name": "Ears relax",
      "clip": "12_Ears_relax"
    },
    {
      "name": "Left paw tap",
      "clip": "13_Left_paw_tap"
    },
    {
      "name": "Right paw tap",
      "clip": "14_Right_paw_tap"
    },
    {
      "name": "Left paw lift",
      "clip": "15_Left_paw_lift"
    },
    {
      "name": "Right paw lift",
      "clip": "16_Right_paw_lift"
    },
    {
      "name": "Left paw reach",
      "clip": "17_Left_paw_reach"
    },
    {
      "name": "Right paw reach",
      "clip": "18_Right_paw_reach"
    },
    {
      "name": "Knead left",
      "clip": "19_Knead_left"
    },
    {
      "name": "Knead right",
      "clip": "20_Knead_right"
    },
    {
      "name": "Back left step",
      "clip": "21_Back_left_step"
    },
    {
      "name": "Back right step",
      "clip": "22_Back_right_step"
    },
    {
      "name": "Back left toe",
      "clip": "23_Back_left_toe"
    },
    {
      "name": "Back right toe",
      "clip": "24_Back_right_toe"
    },
    {
      "name": "Tail left",
      "clip": "25_Tail_left"
    },
    {
      "name": "Tail right",
      "clip": "26_Tail_right"
    },
    {
      "name": "Tail tip curl",
      "clip": "27_Tail_tip_curl"
    },
    {
      "name": "Tail ripple",
      "clip": "28_Tail_ripple"
    },
    {
      "name": "Shoulder sway",
      "clip": "29_Shoulder_sway"
    },
    {
      "name": "Blink",
      "clip": "30_Blink"
    },
    {
      "name": "Wink left",
      "clip": "31_Wink_left"
    },
    {
      "name": "Wink right",
      "clip": "32_Wink_right"
    }
  ],
  "Kira_movements.json": [
    {
      "name": "Golden hello",
      "clip": "Kira_01_Golden_hello"
    },
    {
      "name": "Curious left listen",
      "clip": "Kira_02_Curious_left_listen"
    },
    {
      "name": "Curious right listen",
      "clip": "Kira_03_Curious_right_listen"
    },
    {
      "name": "Soft chin tuck",
      "clip": "Kira_04_Soft_chin_tuck"
    },
    {
      "name": "Scent the air",
      "clip": "Kira_05_Scent_the_air"
    },
    {
      "name": "Bird watch left",
      "clip": "Kira_06_Bird_watch_left"
    },
    {
      "name": "Bird watch right",
      "clip": "Kira_07_Bird_watch_right"
    },
    {
      "name": "Little chirp",
      "clip": "Kira_08_Little_chirp"
    },
    {
      "name": "Sleepy blink",
      "clip": "Kira_09_Sleepy_blink"
    },
    {
      "name": "Left slow wink",
      "clip": "Kira_10_Left_slow_wink"
    },
    {
      "name": "Right slow wink",
      "clip": "Kira_11_Right_slow_wink"
    },
    {
      "name": "Both ears swivel",
      "clip": "Kira_12_Both_ears_swivel"
    },
    {
      "name": "Left listening flick",
      "clip": "Kira_13_Left_listening_flick"
    },
    {
      "name": "Right listening flick",
      "clip": "Kira_14_Right_listening_flick"
    },
    {
      "name": "Ears soften",
      "clip": "Kira_15_Ears_soften"
    },
    {
      "name": "Left paw curl",
      "clip": "Kira_16_Left_paw_curl"
    },
    {
      "name": "Right paw curl",
      "clip": "Kira_17_Right_paw_curl"
    },
    {
      "name": "Velvet knead left",
      "clip": "Kira_18_Velvet_knead_left"
    },
    {
      "name": "Velvet knead right",
      "clip": "Kira_19_Velvet_knead_right"
    },
    {
      "name": "Groom left paw",
      "clip": "Kira_20_Groom_left_paw"
    },
    {
      "name": "Groom right paw",
      "clip": "Kira_21_Groom_right_paw"
    },
    {
      "name": "Playful left bat",
      "clip": "Kira_22_Playful_left_bat"
    },
    {
      "name": "Playful right bat",
      "clip": "Kira_23_Playful_right_bat"
    },
    {
      "name": "Shoulder settle",
      "clip": "Kira_24_Shoulder_settle"
    },
    {
      "name": "Hip shift left",
      "clip": "Kira_25_Hip_shift_left"
    },
    {
      "name": "Hip shift right",
      "clip": "Kira_26_Hip_shift_right"
    },
    {
      "name": "Question mark tail",
      "clip": "Kira_27_Question_mark_tail"
    },
    {
      "name": "Tail tip greeting",
      "clip": "Kira_28_Tail_tip_greeting"
    },
    {
      "name": "Tail ribbon left",
      "clip": "Kira_29_Tail_ribbon_left"
    },
    {
      "name": "Tail ribbon right",
      "clip": "Kira_30_Tail_ribbon_right"
    },
    {
      "name": "Happy tail tremble",
      "clip": "Kira_31_Happy_tail_tremble"
    },
    {
      "name": "Drowsy goodnight",
      "clip": "Kira_32_Drowsy_goodnight"
    }
  ]
};
