import { useState } from 'react';
import { MODEL_ASSETS, resolveChannel, mappingDocument, parseMapping, type ModelKind, type ModelSettings, type ObjFinish } from '../lib/modelChannels';
export default function ModelChannelControls({kind,settings,onChange,channels,onImport}:{kind:ModelKind;settings:ModelSettings;onChange:(s:ModelSettings)=>void;channels:number[];onImport:(kind:ModelKind,s:ModelSettings)=>void}){
 const [name,setName]=useState('Pavane'),[message,setMessage]=useState('');
 const pool=MODEL_ASSETS.filter(a=>a.kind===kind);
 const update=(channel:number,patch:object)=>onChange({...settings,channels:{...settings.channels,[channel]:{...settings.channels[channel],...patch}}});
 const selectStyle='w-full rounded bg-slate-800 px-2 py-1 text-xs text-white';
 return <div className="mt-2 space-y-2 rounded border border-white/10 p-2 text-xs text-white/75">
  <div className="flex gap-2"><button onClick={()=>onChange({...settings,seed:Math.floor(Math.random()*0x7fffffff),movement:'channel',channels:{}})} className="rounded bg-white/10 p-2">Random per channel</button>{kind==='glb'&&<button onClick={()=>onChange({...settings,seed:Math.floor(Math.random()*0x7fffffff),movement:'channel',channels:Object.fromEntries(channels.map(c=>[c,{asset:resolveChannel(settings,kind,c).asset?.file}]))})} className="rounded bg-white/10 p-2">Shuffle movements</button>}</div>
  {kind==='glb'&&<label className="block">Movement override<select aria-label="GLB movement override" className={selectStyle} value={settings.movement} onChange={e=>onChange({...settings,movement:e.target.value})}><option value="channel">Per-channel movements</option>{Array.from(new Map(pool.flatMap(a=>a.movements).map(m=>[m.clip,m])).values()).map(m=><option key={m.clip} value={m.clip}>{m.name}</option>)}</select></label>}
  {kind==='obj'&&<label className="block">OBJ finish<select aria-label="OBJ finish" className={selectStyle} value={settings.finish??'auto'} onChange={e=>onChange({...settings,finish:e.target.value as ObjFinish})}><option value="auto">Auto: MTL when authored, app material for stand-in MTLs</option><option value="app">App materials on every OBJ</option><option value="mtl">MTL colors on every OBJ</option></select><span className="block text-white/40">App materials follow the Output material profile; Auto rotates the profiles per channel.</span></label>}
  <label className="flex gap-2"><input type="checkbox" checked={settings.labels} onChange={e=>onChange({...settings,labels:e.target.checked})}/>Show note labels</label>
  <label className="block">Audition velocity: {settings.velocity}<input aria-label="Audition velocity" className="w-full" type="range" min="1" max="127" value={settings.velocity} onChange={e=>onChange({...settings,velocity:+e.target.value})}/></label>
  <button className="rounded bg-white/10 p-2" onClick={()=>onChange({...settings,solo:!settings.solo})}>{settings.solo?'Show channel grid':'Inspect one model'}</button>
  <div className="max-h-64 overflow-y-auto space-y-2">{channels.map(channel=>{const resolved=resolveChannel(settings,kind,channel);return <div key={channel} className="border-t border-white/10 pt-2"><label>Channel {channel+1}<select aria-label={`Channel ${channel+1} ${kind.toUpperCase()} model`} className={selectStyle} value={settings.channels[channel]?.asset??'random'} onChange={e=>update(channel,{asset:e.target.value==='random'?undefined:e.target.value,movement:undefined})}><option value="random">Random → {resolved.asset?.file??'No models'}</option>{pool.map(a=><option key={a.file}>{a.file}</option>)}</select></label>{kind==='glb'&&<label>Movement<select aria-label={`Channel ${channel+1} movement`} className={selectStyle} value={settings.channels[channel]?.movement??'random'} onChange={e=>update(channel,{movement:e.target.value})}><option value="random">Random → {resolved.asset?.movements.find(m=>m.clip===resolved.movement)?.name??'Embedded clip / static'}</option>{resolved.asset?.movements.map(m=><option key={m.clip} value={m.clip}>{m.name}</option>)}</select></label>}</div>;})}</div>
  <label>Mapping name<input aria-label="Mapping name" className={selectStyle} value={name} onChange={e=>setName(e.target.value)}/></label>
  <div className="flex gap-2"><button className="rounded bg-white/10 p-2" onClick={()=>{const filename=(name.trim().replace(/(?:_mappings)?\.json$/i,'').replace(/_mappings$/i,'')||'3D_to_channel').replace(/[^\w-]/g,'_')+'_mappings.json';const doc=mappingDocument(name,kind,settings,channels);const url=URL.createObjectURL(new Blob([JSON.stringify(doc,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage(`Saved ${filename}`);}}>Save mappings</button><label className="rounded bg-white/10 p-2 cursor-pointer">Load mappings<input aria-label="Load channel mappings" type="file" accept=".json" className="hidden" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;try{const parsed=parseMapping(JSON.parse(await file.text()));onImport(parsed.kind,{...settings,channels:parsed.channels,seed:parsed.seed,movement:'channel'});setName(parsed.name);setMessage(`Loaded ${file.name}`);}catch(err){setMessage(err instanceof Error?err.message:'Invalid mapping file');}e.target.value='';}}/></label></div>
  {message&&<p role="status">{message}</p>}<p className="text-white/40">Hold a visible model to audition. Saved mappings contain exact channel choices.</p>
 </div>;
}
