import {readdir,readFile,writeFile} from 'node:fs/promises';
const base=new URL('../public/demo/meshes/',import.meta.url);
const names=(await readdir(base)).sort();
const files=names.filter(n=>/\.(glb|obj)$/.test(n));
const movements={};
for(const name of names.filter(n=>n.endsWith('_movements.json'))){
 const data=JSON.parse(await readFile(new URL(name,base),'utf8'));
 if(!Array.isArray(data)||data.some(m=>typeof m.name!=='string'||typeof m.clip!=='string'))throw Error(`Invalid movement catalog: ${name}`);
 movements[name]=data.map(({name,clip})=>({name,clip}));
}
await writeFile(new URL('../src/lib/modelAssetManifest.ts',import.meta.url),'// Generated by npm run models:catalog. Source: public/demo/meshes.\nexport const MODEL_FILES = '+JSON.stringify(files,null,2)+';\nexport const MODEL_MOVEMENTS: Record<string, {name:string;clip:string}[]> = '+JSON.stringify(movements,null,2)+';\n');
console.log(`Model catalog: ${files.filter(f=>f.endsWith('.glb')).length} GLB, ${files.filter(f=>f.endsWith('.obj')).length} OBJ.`);
